#!/bin/sh

set -e

if tmux has-session -t mail 2> /dev/null; then
  $HOME/bin/switch_or_attach mail
  exit
fi

tmux new-session -d -s mail -n mutt

tmux send-keys -t mail:mutt "mutt" Enter
$HOME/bin/switch_or_attach mail:mutt.left
