#!/bin/sh

set -e
if test "$1" = ''; then
    echo "please provide one of the following as an argument:"
    find ~/Sites -maxdepth 2 -type d  -name 'wp-content'| cut -d '/' -f 5 | sort
    exit
fi

if tmux has-session -t $1 2> /dev/null; then
  $HOME/bin/switch_or_attach $1
  exit
fi

tmux new-session -c "$HOME/Sites/" -d -s $1 -n dev
tmux send-keys -t $1:dev "cd $HOME/Sites/$1/wp-content/themes" Enter
tmux send-keys -t $1:dev "vim $HOME/Sites/$1/wp-content/themes" Enter

tmux new-window -t $1 -c "$HOME/Sites" -n shell
if [[ -z $(pgrep httpd) && -z $(pgrep mysqld) ]] ; then
    tmux send-keys -t $1:shell "server-up" Enter
fi


tmux new-window -t $1 -c "$HOME/Sites" -n hangups
tmux send-keys -t $1:hangups "$HOME/Sites/hangups/bin/hangups" Enter

tmux new-window -t $1 -c "$HOME/Sites/" -n sass
tmux send-keys -t $1:sass "cd $HOME/Sites/$1/wp-content/themes" Enter

tmux new-window -t $1 -c "$HOME/Sites" -n chrome
tmux send-keys -t $1:chrome "nohup google-chrome-beta --incognito http://tbs.local &" Enter
tmux send-keys -t $1:chrome "nohup google-chrome-beta --incognito http://tbs.local/wp-admin &" Enter
tmux send-keys -t $1:chrome "exit" Enter
$HOME/bin/switch_or_attach $1:shell.left
